spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123
    url: jdbc:mysql://127.0.0.1:3306/SpringCloud_Sell?characterEncding=utf-8&useSSL=false
  jpa:
    show-sql: true
env:
  test3
girl:
  name: Sophie
  age: 24
#PRODUCT:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
